spring:
  datasource:
    url: jdbc:postgresql://${EXPENSE_DB_HOST:localhost}:${EXPENSE_DB_PORT:5433}/expense-tracker-db
    username: ${EXPENSE_DB_USER:postgres}
    password: ${EXPENSE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

jwt:
  secret:
    access: ${JWT_ACCESS_KEY}
    refresh: ${JWT_REFRESH_KEY}
  token:
    lifetime-in-hours: 24
    lifetime-in-days: 30

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: ${TELEGRAM_BOT_NAME}
