eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret:
    access: ${JWT_ACCESS_KEY}

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
