spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0

jpa:
  show-sql: true

default-category:
  categories:
    -
      name: Зарплата
      type: INCOME
    -
      name: Продукти
      type: EXPENSE
    -
      name: Кафе/ресторани
      type: EXPENSE
    -
      name: Транспорт
      type: EXPENSE
    -
      name: Комунальні послуги
      type: EXPENSE
    -
      name: Одяг
      type: EXPENSE
    -
      name: Техніка
      type: EXPENSE
    -
      name: Розваги
      type: EXPENSE
