spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0

default-category:
  categories:
    -
      name: Salary
      type: INCOME
    -
      name: Grocery
      type: EXPENSE
    -
      name: Transport
      type: EXPENSE
    -
      name: Apartments
      type: EXPENSE
    -
      name: Clothes
      type: EXPENSE
    -
      name: Entertainment
      type: EXPENSE
