eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:postgresql://${EXPENSE_DB_HOST:localhost}:${EXPENSE_DB_PORT:5432}/${EXPENSE_DB:expense-tracker-db}
    username: ${EXPENSE_DB_USER:postgres}
    password: ${EXPENSE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.yaml

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

jwt:
  secret:
    access: ${JWT_ACCESS_KEY}
    refresh: ${JWT_REFRESH_KEY}
  token:
    lifetime-in-hours: 24
    lifetime-in-days: 30

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: ${TELEGRAM_BOT_NAME}

filters:
  authorization-header:
    header-value: ${INTERNAL_KEY_HEADER:X-INTERNAL-KEY}

default-category:
  categories:
    -
      name: Зарплата
      type: INCOME
    -
      name: Продукти
      type: EXPENSE
    -
      name: Транспорт
      type: EXPENSE
    -
      name: Комунальні послуги
      type: EXPENSE

recent-activity:
  activityDays: 30

admin:
  allowed_users:
    RedArt02, admin

long-polling:
  tracker:
    period-of-inactivity: 10_000
