eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "telegram-bot-service"
    description: "Expense Tracker Telegram Bot Application"
    version: "1.0.0"

spring:
  datasource:
    url: jdbc:postgresql://${TELEGRAM_DB_HOST:localhost}:${TELEGRAM_DB_PORT:5432}/${TELEGRAM_DB:telegram-bot-db}
    username: ${TELEGRAM_DB_USER:postgres}
    password: ${TELEGRAM_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.yaml

bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}
  api:
    url: https://api.telegram.org
  voice:
    max_length: 10

max-mailing-messages:
  maxMessagesOfAnnouncePerSecond: 25

authorization-header:
  header-value: ${INTERNAL_KEY_HEADER:X-INTERNAL-KEY}

orchestrator:
  host: ${ORCHESTRATOR_HOST:host}
