eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:${MONGODB_PORT:27017}/${MONGODB_DATABASE:telegram-bot-db}?authSource=admin

bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}
  api:
    url: https://api.telegram.org
  voice:
    max_length: 15

max-mailing-messages:
  maxMessagesOfAnnouncePerSecond: 25

authorization-header:
  header-value: ${INTERNAL_KEY_HEADER:X-INTERNAL-KEY}

orchestrator:
  host: ${ORCHESTRATOR_HOST:host}
